[theme]
base = "light"

# Optional: customize specific colors
primaryColor = "#FF4B4B"  # Main accent color
backgroundColor = "#FFFFFF"  # Background color
secondaryBackgroundColor = "#F0F2F6"  # Secondary background color
textColor = "#262730"  # Text color
font = "sans serif"  # Font style